export const Colors={
    white:"#FFFFFF",
    black:'#000',
    dark:'#000',
    red: 'red',
    green: 'green',
    primary:"#FC8415",
    gray:"#666",
    bgColor:"#ffffff",
    purple:"#AD40AF",
    orange:'#F17120',
    grey:'#F5F5F5',
    commonCardShadodow: '#CBD5E1',
    commonShadodowBackground: '#F8FAFC',
    commonBlack:'#1E293E',
    grey1:'#D9D9D9',
    grey2:'#E9EFF6',
    gray3:"#EBEBEB",
    gray4:"#EFECE5",

    darkGrey:"#777777",
    red:"red",
    white1:"#fafaf6",

    //-------Common App Colors-----------
    commonAppBackground: '#E2E8F0',
    commonCardBackground: '#FBFCFD',
    CommonBorderGrey: '#E9EFF6',
    commonTextBlack: '#1E293B',
    CommonTextGrey: '#AAAA',
}