# Generated by Django 4.1.3 on 2023-02-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256, null=True)),
                ('user_phone', models.CharField(max_length=256, null=True)),
                ('user_password', models.CharField(max_length=256, null=True)),
                ('user_created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_tank',
            },
        ),
    ]
