# Generated by Django 3.2.18 on 2023-04-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_id', models.CharField(max_length=256, null=True, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=256, null=True, unique=True)),
                ('group_name', models.CharField(max_length=256, null=True)),
                ('group_description', models.CharField(max_length=256, null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
                ('group_created_by', models.CharField(max_length=256, null=True)),
                ('is_delete', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='TempOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_unique_id', models.CharField(max_length=256, null=True)),
                ('user_phone', models.CharField(max_length=256, null=True)),
                ('user_id', models.CharField(max_length=256, null=True)),
                ('secret_key', models.CharField(max_length=256, null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temp_otp',
            },
        ),
        migrations.CreateModel(
            name='UsersID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=512, unique=True)),
                ('user_phone', models.CharField(max_length=256, null=True)),
                ('user_created_on', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=512, null=True)),
                ('nation', models.CharField(max_length=256, null=True)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'users_ids',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergroup_id', models.CharField(max_length=256, null=True)),
                ('is_delete', models.BooleanField(default=False, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.group', to_field='group_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usersid', to_field='user_id')),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='ExpensesShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_shares_id', models.CharField(max_length=256, null=True)),
                ('amount', models.FloatField()),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
                ('expenses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.expenses', to_field='expenses_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usersid', to_field='user_id')),
            ],
            options={
                'db_table': 'expenses_shares',
            },
        ),
        migrations.AddField(
            model_name='expenses',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.group', to_field='group_id'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usersid', to_field='user_id'),
        ),
    ]
