# Generated by Django 4.1.3 on 2023-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersid',
            name='is_activate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
