# Generated by Django 4.1.3 on 2023-02-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_id', models.CharField(max_length=256, null=True)),
                ('user_phone', models.CharField(max_length=256, null=True)),
                ('user_opt', models.CharField(max_length=256, null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temp_otp',
            },
        ),
    ]
