# Generated by Django 4.1.3 on 2023-02-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tempotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempotp',
            old_name='user_opt',
            new_name='user_otp',
        ),
    ]
