# Generated by Django 4.1.3 on 2023-05-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usersid_is_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('mail', models.CharField(max_length=256, null=True)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('gender', models.CharField(max_length=256, null=True)),
                ('account_verified', models.BooleanField(default=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usersid', to_field='user_id')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
