# Generated by Django 4.1.3 on 2023-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='expensesshares',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
