# Generated by Django 4.1.3 on 2023-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_user_opt_tempotp_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempotp',
            name='user_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
