# Generated by Django 4.1.3 on 2023-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_tempotp_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=256, null=True)),
                ('group_name', models.CharField(max_length=256, null=True)),
                ('group_description', models.CharField(max_length=256, null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
