# Generated by Django 4.1.3 on 2023-02-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_group_group_id_alter_usergroup_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
