# Generated by Django 4.1.3 on 2023-02-05 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users', to_field='user_id'),
        ),
    ]
