# Generated by Django 4.1.3 on 2023-02-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_usergroup_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_id', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('amount', models.CharField(max_length=256, null=True)),
                ('date', models.DateField(null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.group', to_field='group_id')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users', to_field='user_id')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
