# Generated by Django 4.1.3 on 2023-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_mail',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
