# Generated by Django 4.1.3 on 2023-02-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_users_first_name_users_last_name_users_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expenses_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ExpensesShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_shares_id', models.CharField(max_length=256, null=True)),
                ('amount', models.DateField(null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
                ('expenses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.expenses', to_field='expenses_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users', to_field='user_id')),
            ],
            options={
                'db_table': 'expenses_shares',
            },
        ),
    ]
