# Generated by Django 4.1.3 on 2023-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_expenses_expenses_id_expensesshares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesshares',
            name='amount',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
