# Generated by Django 4.1.3 on 2023-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_usergroup_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_created_by',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
