# Generated by Django 4.1.3 on 2023-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_group_group_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempotp',
            old_name='otp_id',
            new_name='otp_expiry_time',
        ),
        migrations.RenameField(
            model_name='tempotp',
            old_name='user_otp',
            new_name='secret_key',
        ),
        migrations.RemoveField(
            model_name='tempotp',
            name='user_phone',
        ),
    ]
