# Generated by Django 4.1.3 on 2023-04-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_rename_otp_id_tempotp_otp_expiry_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempotp',
            old_name='otp_expiry_time',
            new_name='otp_unique_id',
        ),
    ]
