# Generated by Django 4.1.3 on 2023-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_users_first_name_remove_users_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
