# Generated by Django 4.1.3 on 2023-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nation',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
