# Generated by Django 4.1.3 on 2023-04-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_users_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='    ',
        ),
    ]
