# Generated by Django 4.1.3 on 2023-04-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
