# Generated by Django 4.1.3 on 2023-04-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_usersid_alter_expenses_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempotp',
            name='user_phone',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
