INVALID_REQUEST_BODY_MESSAGE = "Invalid request body"
INTERNAL_SERVER_ERROR_MESSAGE = "Internal server error"
SUCCESS_MESSAGE = "success"
STATUS_KEY ="status"
ERROR_KEY = "error"
ERROR_MESSAGE = "error"
DATA_MESSAGE = "data"
DATA_UPDATE_SUCCESSFULLY_MESSAGE = "Data updated successfully"
DATE_ALREADY_EXIST_MESSAGE= "Data already exist"
TOKEN_MESSAGE = "token"
APP_ID_MESSAGE = "app_id"
GROUP_DELETED_MESSAGE ="Group deleted"
GROUP_NOT_EXIST_MESSAGE = "Group not exist"
USER_DELETE_FROM_GROUP_MESSAGE = "User deleted successfully"
ACCOUNT_DOES_NOT_EXIST_DO_SIGN_UP= "No Account Found, Please SignUp!"
ACCOUNT_ALREADY_EXIST_DO_SIGN_IN= "Account already exist, Please SignIn!"


